# Generated by Django 4.2.9 on 2026-06-30 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0038_systemsettings_winrm_password_encrypted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PcJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('copy_file', 'Скопировать файл'), ('run_script', 'Выполнить скрипт')], max_length=20, verbose_name='Тип')),
                ('script_kind', models.CharField(blank=True, choices=[('powershell', 'PowerShell'), ('cmd', 'cmd')], max_length=20, verbose_name='Вид скрипта')),
                ('script_text', models.TextField(blank=True, verbose_name='Текст скрипта')),
                ('file', models.FileField(blank=True, null=True, upload_to='pc_jobs/', verbose_name='Файл')),
                ('dest_path', models.CharField(blank=True, max_length=500, verbose_name='Путь назначения')),
                ('target_mode', models.CharField(choices=[('server', 'Сервер'), ('kassa', 'Кассы'), ('both', 'Сервер + кассы')], default='server', max_length=10, verbose_name='Цель')),
                ('client_ids', models.JSONField(default=list, verbose_name='Клиенты (снимок выбора)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('done', 'Завершено'), ('cancelled', 'Отменено'), ('error', 'Ошибка')], default='pending', max_length=12, verbose_name='Статус')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс, %')),
                ('total_targets', models.PositiveIntegerField(default=0, verbose_name='Всего целей')),
                ('done_targets', models.PositiveIntegerField(default=0, verbose_name='Обработано')),
                ('ok_targets', models.PositiveIntegerField(default=0, verbose_name='Успешно')),
                ('err_targets', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('cancel_requested', models.BooleanField(default=False, verbose_name='Запрошена отмена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задание на ПК',
                'verbose_name_plural': 'Задания на ПК',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PcJobTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_address', models.CharField(blank=True, max_length=500, verbose_name='Адрес аптеки')),
                ('role', models.CharField(max_length=10, verbose_name='Роль')),
                ('ip', models.CharField(blank=True, max_length=45, verbose_name='IP')),
                ('transport', models.CharField(blank=True, max_length=10, verbose_name='Транспорт')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('success', 'Успех'), ('error', 'Ошибка'), ('unreachable', 'Недоступен'), ('skipped', 'Пропущено')], default='pending', max_length=12, verbose_name='Статус')),
                ('exit_code', models.IntegerField(blank=True, null=True, verbose_name='Код возврата')),
                ('result_message', models.TextField(blank=True, verbose_name='Результат')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='pcmgmt.pcjob')),
            ],
            options={
                'verbose_name': 'Цель задания',
                'verbose_name_plural': 'Цели задания',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['job', 'status'], name='pcmgmt_pcjo_job_id_3c4032_idx')],
            },
        ),
    ]
