# Generated by Django 4.2.9 on 2026-07-01 01:59

import apps.pcmgmt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcjob',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.pcmgmt.models.pc_job_upload_to, verbose_name='Файл'),
        ),
    ]
