# Generated by Django 4.2.9 on 2026-07-01 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcmgmt', '0002_alter_pcjob_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcjob',
            name='repeat_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repeats', to='pcmgmt.pcjob'),
        ),
    ]
