# Generated by Django 4.2.9 on 2026-07-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmgmt', '0003_pcjob_repeat_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcjob',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
    ]
