# Generated by Django 4.2.9 on 2026-08-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmgmt', '0004_pcjob_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcjob',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название'),
        ),
    ]
