# Generated by Django 4.2.9 on 2026-06-16 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0037_ofdcompany_inn_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=36, unique=True, verbose_name='UUID устройства')),
                ('registry_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='РНМ')),
                ('factory_number', models.CharField(blank=True, max_length=50, verbose_name='Заводской номер')),
                ('fn_number', models.CharField(blank=True, max_length=50, verbose_name='Номер ФН')),
                ('kkt_name', models.CharField(blank=True, max_length=200, verbose_name='Модель ККТ')),
                ('ffd_version', models.CharField(blank=True, max_length=10, verbose_name='Версия ФФД')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('fiscal_address', models.TextField(blank=True, verbose_name='Адрес установки')),
                ('ip_address', models.CharField(blank=True, max_length=45, verbose_name='IP устройства')),
                ('comproxy_version', models.CharField(blank=True, max_length=50, verbose_name='Версия ComProxy')),
                ('firmware_version', models.CharField(blank=True, max_length=50, verbose_name='Версия прошивки')),
                ('fito_version', models.CharField(blank=True, max_length=50, verbose_name='Версия FITO')),
                ('raw_cash_info', models.JSONField(blank=True, default=dict, verbose_name='Полный cash_info_report')),
                ('raw_registration_report', models.JSONField(blank=True, default=dict, verbose_name='Полный registration_report')),
                ('supported_methods', models.JSONField(blank=True, default=dict, verbose_name='Методы из handshake')),
                ('match_method', models.CharField(blank=True, choices=[('auto', 'Автоматически'), ('manual', 'Вручную')], max_length=20, verbose_name='Способ привязки')),
                ('matched_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата привязки')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='Первое появление')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Последний отклик')),
                ('cash_info_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний cash_info_report')),
                ('kkt_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_devices', to='clients.kktdata', verbose_name='Привязанная ККТ')),
            ],
            options={
                'verbose_name': 'Устройство ComProxy',
                'verbose_name_plural': 'Устройства ComProxy',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='ProxyTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_status', models.CharField(blank=True, max_length=10, verbose_name='Статус смены')),
                ('shift_exceeded_24h', models.BooleanField(default=False, verbose_name='Смена > 24ч')),
                ('kkt_flags_fatal', models.IntegerField(default=0, verbose_name='Фатальные флаги')),
                ('kkt_flags_current', models.IntegerField(default=0, verbose_name='Текущие флаги')),
                ('fn_flags', models.IntegerField(default=0, verbose_name='Флаги ФН')),
                ('unsent_ofd_count', models.IntegerField(default=0, verbose_name='Неотправленных в ОФД')),
                ('unsent_oism_count', models.IntegerField(default=0, verbose_name='Неотправленных в ОИСМ')),
                ('raw_counters', models.JSONField(blank=True, default=dict, verbose_name='Полный counters_report')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='comproxy.proxydevice', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Телеметрия ComProxy',
                'verbose_name_plural': 'Телеметрия ComProxy',
            },
        ),
    ]
