# Generated by Django 4.2.9 on 2026-06-16 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comproxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('COMPROXY', 'ComProxy'), ('FIRMWARE', 'Прошивка ККТ')], max_length=20, verbose_name='Тип')),
                ('version', models.CharField(max_length=50, verbose_name='Версия')),
                ('version_from', models.CharField(blank=True, max_length=50, verbose_name='Совместимо с версии')),
                ('project', models.CharField(default='CSI', max_length=50, verbose_name='Проект')),
                ('product', models.CharField(default='ComProxy', max_length=50, verbose_name='Продукт')),
                ('file', models.FileField(upload_to='comproxy/updates/', verbose_name='Файл')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер (байт)')),
                ('md5', models.CharField(blank=True, max_length=32, verbose_name='MD5')),
                ('info', models.TextField(blank=True, verbose_name='Описание')),
                ('enabled', models.BooleanField(default=True, verbose_name='Активен')),
                ('barrier', models.BooleanField(default=False, verbose_name='Барьерное обновление')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Пакет обновления',
                'verbose_name_plural': 'Пакеты обновлений',
                'ordering': ['-created_at'],
                'unique_together': {('product_type', 'project', 'product', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DeviceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='ID задачи')),
                ('task_type', models.CharField(default='update_software', max_length=50, verbose_name='Тип задачи')),
                ('task_data', models.JSONField(default=dict, verbose_name='Payload')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('SENT', 'Отправлена'), ('SUCCESS', 'Успешно'), ('ERROR', 'Ошибка'), ('CANCELLED', 'Отменена')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('result_message', models.TextField(blank=True, verbose_name='Результат')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлена')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='comproxy.proxydevice', verbose_name='Устройство')),
                ('update_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='comproxy.updatepackage', verbose_name='Пакет обновления')),
            ],
            options={
                'verbose_name': 'Задача устройства',
                'verbose_name_plural': 'Задачи устройств',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'status'], name='comproxy_de_device__49417e_idx')],
            },
        ),
    ]
