# Generated by Django 4.2.9 on 2026-02-20 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название провайдера')),
                ('connection_type', models.CharField(blank=True, choices=[('fiber', 'Оптоволокно'), ('dsl', 'DSL'), ('cable', 'Кабель'), ('wireless', 'Беспроводное'), ('satellite', 'Спутниковое'), ('other', 'Другое')], max_length=50, verbose_name='Тип подключения')),
                ('contract', models.CharField(blank=True, max_length=200, verbose_name='Контракт / Договор')),
                ('network_settings', models.TextField(blank=True, verbose_name='Настройки сети')),
                ('support_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон техподдержки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Провайдер',
                'verbose_name_plural': 'Провайдеры',
            },
        ),
    ]
