# Generated by Django 4.2.9 on 2026-02-20 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['name'], 'verbose_name': 'Провайдер', 'verbose_name_plural': 'Провайдеры'},
        ),
        migrations.RemoveField(
            model_name='provider',
            name='client',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='support_phone',
        ),
        migrations.AddField(
            model_name='client',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='clients.provider', verbose_name='Провайдер'),
        ),
        migrations.AddField(
            model_name='provider',
            name='support_phones',
            field=models.TextField(blank=True, verbose_name='Телефоны техподдержки'),
        ),
    ]
