# Generated by Django 4.2.9 on 2026-02-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_provider_options_remove_provider_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='client',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='№ договора'),
        ),
        migrations.AddField(
            model_name='client',
            name='inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='client',
            name='personal_account',
            field=models.CharField(blank=True, max_length=100, verbose_name='Лицевой счёт'),
        ),
    ]
