# Generated by Django 4.2.9 on 2026-02-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_client_assigned_to_client_contract_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='network_settings',
        ),
        migrations.AddField(
            model_name='provider',
            name='provider_settings',
            field=models.TextField(blank=True, verbose_name='Настройки провайдера'),
        ),
        migrations.AddField(
            model_name='provider',
            name='subnet',
            field=models.TextField(blank=True, verbose_name='Подсеть аптеки'),
        ),
    ]
