# Generated by Django 4.2.9 on 2026-02-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_provider_network_settings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='provider_settings',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='subnet',
        ),
        migrations.AddField(
            model_name='client',
            name='provider_settings',
            field=models.TextField(blank=True, verbose_name='Настройки провайдера'),
        ),
        migrations.AddField(
            model_name='client',
            name='subnet',
            field=models.TextField(blank=True, verbose_name='Подсеть аптеки'),
        ),
    ]
