# Generated by Django 4.2.9 on 2026-02-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_provider_provider_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='external_ip',
            field=models.CharField(blank=True, max_length=50, verbose_name='Внешний IP'),
        ),
        migrations.AlterField(
            model_name='client',
            name='subnet',
            field=models.CharField(blank=True, max_length=50, verbose_name='Подсеть аптеки'),
        ),
        migrations.AlterField(
            model_name='clientactivity',
            name='action',
            field=models.CharField(max_length=500, verbose_name='Действие'),
        ),
    ]
