# Generated by Django 4.2.9 on 2026-02-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_external_ip_alter_client_subnet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='iccid',
            field=models.CharField(blank=True, max_length=30, verbose_name='ICCID'),
        ),
        migrations.AddField(
            model_name='client',
            name='pharmacy_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Код аптеки'),
        ),
    ]
