# Generated by Django 4.2.9 on 2026-02-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_client_first_name_alter_client_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='connection_type',
        ),
        migrations.AddField(
            model_name='client',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('fiber', 'Оптоволокно'), ('dsl', 'DSL'), ('cable', 'Кабель'), ('wireless', 'Беспроводное')], max_length=50, verbose_name='Тип подключения'),
        ),
    ]
