# Generated by Django 4.2.9 on 2026-02-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_remove_provider_connection_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tariff',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тариф'),
        ),
    ]
