# Generated by Django 4.2.9 on 2026-02-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_client_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='provider_equipment',
            field=models.BooleanField(default=False, verbose_name='Оборудование провайдера'),
        ),
    ]
