# Generated by Django 4.2.9 on 2026-02-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_clientfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
    ]
