# Generated by Django 4.2.9 on 2026-02-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_client_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('fiber', 'Оптоволокно'), ('dsl', 'DSL'), ('cable', 'Кабель'), ('wireless', 'Беспроводное'), ('modem', 'Модем'), ('mrnet', 'MR-Net')], max_length=50, verbose_name='Тип подключения'),
        ),
    ]
