# Generated by Django 4.2.9 on 2026-02-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_alter_client_connection_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssh_user', models.CharField(blank=True, max_length=100, verbose_name='SSH пользователь')),
                ('ssh_password_encrypted', models.TextField(blank=True, verbose_name='SSH пароль (зашифрован)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки системы',
                'verbose_name_plural': 'Настройки системы',
            },
        ),
    ]
