# Generated by Django 4.2.9 on 2026-02-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='modem_iccid',
            field=models.CharField(blank=True, max_length=100, verbose_name='ICCID модема'),
        ),
        migrations.AddField(
            model_name='client',
            name='modem_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер модема/SIM'),
        ),
    ]
