# Generated by Django 4.2.9 on 2026-02-23 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0021_calendarevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('duty_type', models.CharField(choices=[('phone', 'Телефон'), ('day', 'Работа днём'), ('phone_day', 'Телефон + день'), ('vacation', 'Отпуск'), ('busy', 'Занят')], max_length=20, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'График дежурств',
                'verbose_name_plural': 'График дежурств',
                'ordering': ['date', 'user'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
    ]
