# Generated by Django 4.2.9 on 2026-02-23 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0022_dutyschedule_delete_calendarevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('is_holiday', models.BooleanField(default=True, verbose_name='Выходной')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Особый день',
                'verbose_name_plural': 'Особые дни',
                'ordering': ['date'],
            },
        ),
    ]
