# Generated by Django 4.2.9 on 2026-03-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_systemsettings_timezone_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='schedule_days',
            field=models.CharField(blank=True, default='0,1,2,3,4', max_length=20, verbose_name='Дни недели (0=пн…6=вс, через запятую)'),
        ),
    ]
