# Generated by Django 4.2.9 on 2026-03-29 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0031_faqfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqfile',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='clients.faqarticle'),
        ),
        migrations.AlterField(
            model_name='faqfile',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
