# Generated by Django 4.2.9 on 2026-03-30 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0032_alter_faqfile_article_alter_faqfile_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqArticleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'создал статью'), ('title', 'изменил заголовок'), ('content', 'изменил содержимое'), ('category', 'изменил категорию')], max_length=20, verbose_name='Действие')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='clients.faqarticle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История изменений FAQ',
                'verbose_name_plural': 'История изменений FAQ',
                'ordering': ['-created_at'],
            },
        ),
    ]
