# Generated by Django 4.2.9 on 2026-06-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0035_systemsettings_allowed_email_domains'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='kktdata',
            constraint=models.UniqueConstraint(condition=models.Q(('kkt_reg_id__gt', '')), fields=('client', 'kkt_reg_id'), name='unique_kkt_per_client'),
        ),
    ]
