# Generated by Django 4.2.9 on 2026-06-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0036_unique_kkt_per_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofdcompany',
            name='inn',
            field=models.CharField(max_length=12, unique=True, verbose_name='ИНН'),
        ),
    ]
