# Generated by Django 4.2.9 on 2026-06-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0037_ofdcompany_inn_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='winrm_password_encrypted',
            field=models.TextField(blank=True, verbose_name='Windows пароль (зашифрован)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='winrm_user',
            field=models.CharField(blank=True, max_length=100, verbose_name='Windows пользователь'),
        ),
    ]
