# Generated by Django 4.2.9 on 2026-07-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0038_systemsettings_winrm_password_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofdcompany',
            name='chz_token_encrypted',
            field=models.TextField(blank=True, verbose_name='Токен ЧЗ (зашифрован)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='regime_password_encrypted',
            field=models.TextField(blank=True, verbose_name='Пароль Regime (зашифрован)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='regime_user',
            field=models.CharField(blank=True, max_length=100, verbose_name='Пользователь Regime'),
        ),
    ]
